### ISSUE TITLE
Create Linux Environment Setup Tutorial for Backend Development

### ISSUE THREAD

**Issue by bounaykut** [bounswe/bounswe2017group10#113]

**Comment by bounaykut** [comment]
[Here](https://github.com/bounswe/bounswe2017group10/wiki/Linux-Backend-Environment-Setup) is the link to tutorial page.

**Comment by yigitozkavci** [comment]
Umm, duplication? #107

**Comment by yigitozkavci** [comment]
Also; @emir350z and @SaitTalhaNisanci were already working on a Linux tutorial AFAIK. It would be better to keep in touch.
