### ISSUE TITLE
Schedule Meeting 2 for Week 2

### ISSUE THREAD

**Issue by egemahlec** [bounswe/bounswe2017group10#12]
Please conduct the poll whose link is given below so that we can find appropriate time slot which is suitable for every group member. 

http://doodle.com/poll/na76eixa7azxm63m

We will close this issue after every group member conduct the poll.

**Comment by yigitozkavci** [comment]
We should be discussing the project description in the meeting. Project file can be found in here: https://piazza.com/boun.edu.tr/spring2017/cmpe352451/resources

**Comment by yigitozkavci** [comment]
We are meeting Friday at 6pm, so I'm closing it? @egem

**Comment by egemahlec** [comment]
As Yigit said, the meeting will be held on Friday at 6pm. Therefore, we are closing this issue. Thank you for joining the poll.
