### ISSUE TITLE
Implement Android login/signup page

### ISSUE THREAD

**Issue by eozd** [bounswe/bounswe2017group10#121]
Android login/signup page should be implemented according to our Android mockups.

**Comment by eozd** [comment]
I have created a prototype for login/signup page, as you can find in fb321003ffb8cf50ffacca0bb8d918c77e3d8052. We can take a look at it in our meeting.

**Comment by mmutas** [comment]
Are we gonna merge this branch to the android-dev?

Nvm. Android-dev is already waiting for PR.

**Comment by eozd** [comment]
No, I was thinking of creating a new pull request solely for reviewing the changes we will make during login activity implementation.

**Comment by eozd** [comment]
First prototype of login/signup page layout is implemented and merged into ```master``` with #132.
