### ISSUE TITLE
Protected branches and merge authorization

### ISSUE THREAD

**Issue by eozd** [bounswe/bounswe2017group10#125]
We can set protected branches, and also enable required reviews in order to merge a pull request. [This github help page](https://help.github.com/articles/defining-the-mergeability-of-pull-requests/) mentions these issues and more, such as status checks which is related to #118.

**Comment by yigitozkavci** [comment]
Actually, after our discussion with @SaitTalhaNisanci about the backend branch, we decided not to have a branch like `backend` for all backend stuff, but instead, create feature branches and merge right into master from them.

If you think we can use the same idea for `mobile`, we can organise pull requests via related **labels** and we don't have to protect and branches.

**Note:** Actually AFAIK you can disable force pushes into specific branches, in which case, we can make use of this in our master branch

**Comment by eozd** [comment]
Label branches is a good idea. From now on, we will use label branches workflow on ```mobile``` as well.

Regarding protected branches, I have just made ```master``` a protected branch which does two things:

* All pull requests must be reviewed before they are merged.
* All commits made after a review will invalidate the previous review. In this case, PR must be reviewed again before it can be merged into ```master```.

There are additional protections we can use for ```master```, such as status checks as mentioned in #118. See [branch protection page](https://github.com/bounswe/bounswe2017group10/settings/branches) for further details.

**Comment by yigitozkavci** [comment]
That's so cool, thanks! I think this sums up all our needs for branch protection
