### ISSUE TITLE
Development and Production Deployments

### ISSUE THREAD

**Issue by eozd** [bounswe/bounswe2017group10#130]
Today, we discussed our development and deployment strategy with @SaitTalhaNisanci and thought that it would be better in the long run if we have development and production separated with separate ```settings.py``` files. This way, we can use debug mode in development mode for easier testing and bug finding. What are your thoughts on this, @yigitozkavci?

**Comment by yigitozkavci** [comment]
Generally, settings like this including database settings are arranged in the following manner:

`DEBUG = ENV['DEBUG'] || False`

That is, it reads the setting from environment variables with a default value.
It's not healthy to hardcode any of these settings. If you can research on how it's done in Django, I would be more than happy to put those variables into server's environment variables.

**Comment by SaitTalhaNisanci** [comment]
Maybe this can be helpful : [url](https://medium.com/@ayarshabeer/django-best-practice-settings-file-for-multiple-environments-6d71c6966ee2)

**Comment by yigitozkavci** [comment]
@eozd Do you think using environment variables solves the problem? I personally don't need settings other than debug and database config

**Comment by eozd** [comment]
@yigitozkavci I believe for now, environment variables is a good enough solution. Later, if we need a more sophisticated one, we can apply a similar solution to the one presented in @SaitTalhaNisanci's link.

Regarding environment variables, we can use them in two ways:
1. Export the variables to all shells such as
```export ATLAS_DEBUG=true```

2. Write separate shell scripts for different configurations. For example,

```atlas_dev.sh```
```
#!/bin/bash
ATLAS_DEBUG=true  # notice we don't export here, just set it for the current shell.
# other variables to be set
# commands to be executed to deploy
```

```atlas_prod.sh```
```
#!/bin/bash
ATLAS_DEBUG=false
# other variables to be set
# commands to be executed to deploy
```
The second way is very similar to the solution @SaitTalhaNisanci presented.

I assume explicitly setting environment variables is a good way of not storing database passwords in the repository. We can combine the above script solution with explicity setting as follows:

3. ```ATLAS_DB_PASSWORD=password ./atlas_prod.sh``` This way, we would get the best of both worlds: Storing static and non-crucial environment variables in scripts, and setting passwords manually.

P.S.: There may be some errors in the commands I have written. Feel free to correct me.

**Comment by yigitozkavci** [comment]
Hmm, for me, it's fine to keep these shell scripts and execute them upon new installation; but it surely will increase the entry barrier for setting up development environment.

What about default settings inside `settings.py` (DEBUG=false, DB_USER=atlas etc.) represent development environment, and we set them manually for production environment? I think indeed we can use a script for production but I'm not sure using one in dev environment is a good idea

**Comment by eozd** [comment]
Yep, debug by default sounds like a good idea.
