### ISSUE TITLE
Read about the Standard Description about the Annotation Model

### ISSUE THREAD

**Issue by YmirKhang** [bounswe/bounswe2017group10#143]
[This](https://www.w3.org/TR/annotation-model/#selectors) link might be very useful for all of us. It has a very detailed desciption of the Data Model and resources for it.

**Comment by yigitozkavci** [comment]
Thanks for the link! How about making it a target and have everyone be read this until our next meeting so that we can discuss about its backend and frontend aspects, as well as storing data publicly?

**Comment by SaitTalhaNisanci** [comment]
Annotation is in progress so closing, and almost done so closing this issue.
