### ISSUE TITLE
Communication Methods

### ISSUE THREAD

**Issue by YmirKhang** [bounswe/bounswe2017group10#16]
Think of alternative communication methods that we can use as a group, so we can discuss them in the next meeting

**Comment by yigitozkavci** [comment]
I suggest Slack as a replacement of whatsapp

**Comment by sezgineray** [comment]
We could give a try to Slack, what advantages does it have over whatsapp or telegram?

**Comment by yigitozkavci** [comment]
It's so much easier to organise channels, which lets us part ourselves into groups & divide context and work on topics. Some example channel ideas:

- General
- API Research (We could have created different channels for each of the apis; ios, android, web etc.)
- Project Requirements
- Project Features

**Comment by yigitozkavci** [comment]
We decided on Slack for inter-team communication. Closing this, okay? @emir350z
