### ISSUE TITLE
Django error reporting

### ISSUE THREAD

**Issue by yigitozkavci** [bounswe/bounswe2017group10#165]
Django has a setting `ADMINS` which it uses to send e-mail whenever an internal server error occurs. I am going to add who is interested in investigating exceptions occured.

Drop your e-mails below until tomorrow night and let's receive those chaotic error e-mails!

**Comment by eozd** [comment]
Count me in

**Comment by yigitozkavci** [comment]
I need your e-mail @eozd :)

**Comment by eozd** [comment]
esref.ozdemir27@gmail.com

**Comment by SaitTalhaNisanci** [comment]
s.talhanisanci@gmail.com

**Comment by bounaykut** [comment]
aykut___1995@hotmail.com

**Comment by eozd** [comment]
@yigitozkavci @SaitTalhaNisanci @bounaykut I can also add the e-mails of all the people here to Travis build status. When a commit fails, it would send us an e-mail. Is it okay for you?
