### ISSUE TITLE
Token signature expiration time needs to be increased

### ISSUE THREAD

**Issue by yigitozkavci** [bounswe/bounswe2017group10#187]
User should stay logged in for at least 1 day, probably 1 week or so would be better.

**Comment by mmutas** [comment]
Afaik, people usually choose token expiration time  around 10 minutes. I dont understand why it would be better 1 day or so

**Comment by yigitozkavci** [comment]
We don't store user credentials on client side, of course, so that means user needs to fill login information every 10 minutes...

Is it possible that you are referring to API tokens with refresh ability? In that case, token can be refreshed programatically, so there is no user side-effect.

**Comment by mmutas** [comment]
Indeed, normally every request that takes token should return a new token.

**Comment by yigitozkavci** [comment]
Um, I don't think that's a practical thing to do. I've never seen applications return tokens for non-authentication endpoints (ie. login, signup). Do you have any examples on such implementation?

**Comment by eozd** [comment]
To achieve this, should we store token on the device on Android side? Additionally, I presume backend should make adjustments on token expiration times?

**Comment by yigitozkavci** [comment]
You cannot keep the user logged in without an authorization token saved in client by the way. That's what token are for. Client stores the token, and forces user to re-authenticate after token has invalidated (expired). Hence, forcing user to re-login every 1 hour (I assume it's around 1 hour now) is a bad experience.

**Comment by mmutas** [comment]
I check a little bit more and as you said people uses more long expiration times. Short intervals are only implemented in banking systems or sth.

**Comment by eozd** [comment]
Do we need to implement any security measures for storing token on user device, because a user with someone else's token can pretty much do everything on our system. And if so, what are you planning to do for frontend?

**Comment by yigitozkavci** [comment]
- Someone who has access to client can already take actions on client machine if client is logged in. I don't know any way to encrypt and use something on client-side besides obscuring the token (which is bad).
- We can ensure that man-in-the-middle attacks won't occur after we use (which we can in the future) SSL on our server; which I don't know even this fully solves the security issue
- We can ensure forgotten auth sessions won't be valid because of token expiration times

As for frontend, I use localStorage, not cookie so that token doesn't go with every request to everywhere; but only when I decide to send token, I send it via `Authorization` header to our server.

**Comment by eozd** [comment]
In a similar fashion, we might use SharedPreferences on android side which is basically an app-specific local key-value storage space. We might refresh the token each time the app is opened.
