### ISSUE TITLE
Formalise communication plan and add it to wiki

### ISSUE THREAD

**Issue by yigitozkavci** [bounswe/bounswe2017group10#19]

**Comment by yigitozkavci** [comment]
Communication plan is here:

Piazza - To talk with the customers
Whatsapp - All the time
Slack - For internal team communication
Github - For project management
Doodle - For scheduling
Skype - For meetings that are not face to face
Drive - Synchronising text while brainstorming in the meetings

**Comment by YmirKhang** [comment]
Should we define our communication audiences? Is Cihat our only customer, or do we also consider Suzan Hoca as our customer?

**Comment by yigitozkavci** [comment]
I think we should also define our audience and Cihat is our only customer

**Comment by egemahlec** [comment]
I agree with Yiğit. We should define our audience in the communication plan by stating that only Cihat is our customer.

**Comment by YmirKhang** [comment]
Will finish the comm. plan tomorrow afternoon. Some feedback would be nice on the currently implemented one.

**Comment by YmirKhang** [comment]
Finished. You can update the page if you have any concerns or anything to add.
