### ISSUE TITLE
Disallow going back to login/signup after successful login

### ISSUE THREAD

**Issue by eozd** [bounswe/bounswe2017group10#193]
A user should not be able to go back to login/signup activity after a successful login. In this case, back button should prompt the user if he/she wants to quit the app.

**Comment by ramazankani** [comment]
[](https://github.com/bounswe/bounswe2017group10/commit/affee602573bbeae76c725c47c0f82a18a391ae2?diff=unified)

ı think I have found a solution to that problem for now. but there is a problem. If you throw the application back and open it again, you need to login again.

**Comment by ramazankani** [comment]
[](https://github.com/bounswe/bounswe2017group10/commit/affee602573bbeae76c725c47c0f82a18a391ae2?diff=unified)

**Comment by ramazankani** [comment]
[here](https://github.com/bounswe/bounswe2017group10/commit/affee602573bbeae76c725c47c0f82a18a391ae2)

**Comment by eozd** [comment]
With SharedPreferences PR (#208), the issue you mention has been solved. Since both problems related to token are resolved, I close this issue.
