### ISSUE TITLE
Preparing Milestone Report

### ISSUE THREAD

**Issue by yigitozkavci** [bounswe/bounswe2017group10#204]
We are expected to prepare a milestone report until this Friday. I say we assign ourselves to several parts of the report, then I can gather them together in a LaTeX document. Here are the topics:

- [Yiğit Özkavcı, Emirhan Karagül, Esref Ozdemir] Executive Summary: Summary of project status and any changes that are planned for moving forward.
- [Emirhan Karagül, Esref Ozdemir] List and status of deliverables (Completed)
- [Esref Ozdemir] Evaluation of the status of deliverables and its impact on plan
- [Yiğit Özkavcı, Emirhan Karagül] A summary of coding work done by each team member (In tabular format)
- Requirements
- [Ali Kaan Gündüz] Design
- [Aykut Bozkurt] Project plan (In tabular format; you may omit Gantt timelines and display dates/durations only as text for readability)
- [Yiğit Özkavcı, Esref Ozdemir] Code will be inspected online and will not be in the delivered report. However, the code structure and group process should be documented, for example if each feature is a branch and what are the branches, how are pull requests used, etc.
- [Yiğit Özkavcı, Emirhan Karagül, Esref Ozdemir] Evaluation of tools and managing the project. This is a lessons learned from the project development decisions made so far. Tools are for planning, IDE, frameworks, and everything. The management is the process used by the team, including how the tools are being effectively utilized. If there are some aspects that are not working out, what kind of changes are planned.

**Comment by YmirKhang** [comment]
[Link](https://www.overleaf.com/11791542cgczmdytzdtr) to the Report

**Comment by alikaang** [comment]
couldn't align my image to design subsection. weird bug?

**Comment by bounaykut** [comment]
Milestone1 pdf is uploaded to [link](https://www.scribd.com/document/363933125/Atlas-Milestone-1)
