### ISSUE TITLE
Media Item Model

### ISSUE THREAD

**Issue by YmirKhang** [bounswe/bounswe2017group10#246]
I have questions about managing the media items in our models. Should we have only one generic model to store all the media items with a field names 'type'. Or should we have seperate models for all media items maybe storing more information about the media item:  
Like a sound item with the field of duration

**Comment by SaitTalhaNisanci** [comment]
Right now we have them separately, even though we dont have video item, image item doesnt extend any model. I am on the side of using them separately as we have started like that.
