### ISSUE TITLE
Content Pagination

### ISSUE THREAD

**Issue by yigitozkavci** [bounswe/bounswe2017group10#252]
I am planning to crawl this website for content populating, and after we have hundreds of cultural heritages, we need to paginate them, possibly with a "load more" button on frontend

**Comment by yigitozkavci** [comment]
This is a task for both frontend and backend. We need the backend specification on pagination first @SaitTalhaNisanci

**Comment by SaitTalhaNisanci** [comment]
@yigitozkavci  Do we want pagination on everything ? Also do we want the same pagination for everything or different pagination for different things ?

**Comment by yigitozkavci** [comment]
Um, not actually. We'll need to paginate only cultural heritages AFAIK. No need for premature optimization if that's the case in backend
