### ISSUE TITLE
Backend Tag Error in all endpoints

### ISSUE THREAD

**Issue by YmirKhang** [bounswe/bounswe2017group10#256]
#### Issue description
- All the endpoints in backend give error including post for creating heritage item and retrieving heritage items.

#### What's the expected result?
- Something about tags is causing internal server error in the backend.
- This must be fixed
#### Additional details / screenshot
![image](https://user-images.githubusercontent.com/23107192/32798449-c7171150-c985-11e7-94d7-0fba89ffd30f.png)
![image](https://user-images.githubusercontent.com/23107192/32798524-04f6e9be-c986-11e7-859c-a8e9b9c4bd1b.png)

**Comment by SaitTalhaNisanci** [comment]
I deleted some migrations because of changing primary key, so I guess you need to clean the database and make migrations from scratch.

**Comment by YmirKhang** [comment]
Okay,  yes now its working but it must be also fixed in the live server @yigitozkavci
