### ISSUE TITLE
Revise the requirements

### ISSUE THREAD

**Issue by yigitozkavci** [bounswe/bounswe2017group10#27]
- [x]  Add user requirements
- [x] Update non-functional system requirements
- [x] Add glossary
- [x] Carry some of the functional requirements to user requirements

Here is the clarifications: #25

**Comment by yigitozkavci** [comment]
We should certainly discuss some of the requirements. I modified non-functional requirements and it seems fine to me now; for the other parts, we can discuss them in Friday meeting.

**Comment by YmirKhang** [comment]
Done
