### ISSUE TITLE
Need whole user data in comment response bodies

### ISSUE THREAD

**Issue by yigitozkavci** [bounswe/bounswe2017group10#274]
Clients don't have data of all the users, and now a comment body looks like this:

```json
      {
        "id": 1,
        "text": "wow",
        "created_time": "2017-11-20",
        "updated_time": "2017-11-20",
        "user": 6,
        "cultural_heritage_item": 3
      }
```

Clients need actual user data, id won't cut it since this will cause n+1 performance issue because of the requests need to be sent.

**Comment by yigitozkavci** [comment]
This also would be applied into cultural heritage response, since I'm aiming to write author's name on cultural heritage listing.

**Comment by SaitTalhaNisanci** [comment]
@yigitozkavci  You can get the user info from `user_info` field. See #318
