### ISSUE TITLE
Get Endpoint for Individual Items

### ISSUE THREAD

**Issue by eozd** [bounswe/bounswe2017group10#287]
#### Issue description
- We need get endpoints for individual items instead of getting all the data for items in a single page. Since we already need an endpoint to track which items a user visits, this would solve both the problems.

**Comment by SaitTalhaNisanci** [comment]
What do you mean by individual items ? Why do we need an endpoint for a user's visited items? I think that is an internal issue. If you are asking that to display their visited items in like profile page that makes sense, but what else would it be necessary for ?

**Comment by eozd** [comment]
The main reason behind this issue is to be able to track which user visits which item. Sending all the data of each item using feed pagination is enough for now. Since we will make a separate endpoint to send which user visits which item for how many seconds with #293, this issue is closed.
