### ISSUE TITLE
Favorite Feature on Backend

### ISSUE THREAD

**Issue by eozd** [bounswe/bounswe2017group10#288]
#### Issue description
- We need an endpoint to favorite an item. This will be a cornerstone of our recommendation system.

**Comment by SaitTalhaNisanci** [comment]
Are we going to have only one favorite item for a user or it is possible to have multiple favorites ?

**Comment by YmirKhang** [comment]
Multiple favourites for sure

**Comment by eozd** [comment]
### Backend Requirements
1. A user should be able to get his/her own favourite items on profile page.
2. When a user views an item, we should be able to show if the current user has this item in his/her favourites.
3. A user should be able to favourite as many items as possible. Favourite is a many-to-many relation between users and heritage items.

### Possible Options for Implementation
1. We might add an additional boolean field to our heritage item JSON, representing if the user that has sent the request has this item in his/her favourites. To implement this, backend will need to inner join the current user id against the list of user ids that has this item in their favourites.
  * Storing, and then returning **in a heritage item JSON**, all the user ids that has an item in their favourites is not a good idea; since a client doesn't need the user ids of all the users that has an item in their favourites.
2. To add an item to favourites, we might use an additional favourite endpoint.
3. We will need an additional get_own_favourites endpoint to get the favourite items of the current user.
