### ISSUE TITLE
Front-end Problem on Chrome

### ISSUE THREAD

**Issue by bounaykut** [bounswe/bounswe2017group10#291]
#### Issue description
- Navbar auto-complete and menu problem on Chrome

#### Steps to reproduce the issue
1. Log into your account
2. Click on auto-complete box or profile in the navbar menu in the main page or in the heritage feed page
3. I got no response, just a blank page

#### What's the expected result?
- To see 10 items according to search text or navigate into profile page

#### What's the actual result?
- Page is blank.

### Platform Details
-  Linux/ubuntu 17.04 lts on Chrome browser

#### Additional details / screenshot
- ![Screenshot]()
-

**Comment by yigitozkavci** [comment]
Can you provide console errors please?

**Comment by bounaykut** [comment]
https://pasteboard.co/GV7eqxT1.png

**Comment by yigitozkavci** [comment]
You should clear your `localState` in your browser. Here is how:

* Open developer console
* Go to `Application` tab
* Expand `Local Storage` from left sidebar under `Storage` category
* Click the one with prefix `http://localhost`
* From right window, click and press delete anything in there.

## Why is this a problem?
We are updating the structure of the state in each deployment. If you have the old state, it conflicts with the new structure. I didn't think of any way of invalidating and flushing the state in case this happens, maybe you can search for it? @bounaykut

**Comment by bounaykut** [comment]
It is OK now. I will have a look at it.
