### ISSUE TITLE
Android View Item Design and Functionality Improvements

### ISSUE THREAD

**Issue by eozd** [bounswe/bounswe2017group10#328]
#### Issue description
- User should be able to see location, start year and end year in ViewItemFragment
- There should be margins between comment part and the description part
- We should show user information (username and profile picture) in each comment header.
- A new ListItemsFragment together with a RecyclerView should be put at the bottom to show the recommended items.

**Comment by mmutas** [comment]
2nd and 3rd bullet is done by #362
