### ISSUE TITLE
Arrangement for the final deliverable

### ISSUE THREAD

**Issue by YmirKhang** [bounswe/bounswe2017group10#407]
So before the final presentation there are some work to do to come up with a desirable ending. So all of us should be concerned about the list below before the final presentation:

- [ ]  Preparing a nice scenario for the demo, which highlights all the necessary functionalities, but nothing more.

- [ ]  Preparing a presentation before the demo. (Short and informative)

- [ ]  Preparing a sceneario and handling the promotion video of the product.

**Comment by alikaang** [comment]
We shall arrange a date for video
