### ISSUE TITLE
Refactor the class diagram

### ISSUE THREAD

**Issue by yigitozkavci** [bounswe/bounswe2017group10#44]
- [x] Draw the initial class diagrams
- [x] Refactor it with the feedbacks
- [x] Connect classes with relations/associations

**Comment by yigitozkavci** [comment]
- In `CulturalHeritage` class, we have `addMediaItem()` method. If only the `owner` of the `CulturalHeritage` is allowed to add a `MediaItem`, then giving a `User` as parameter is redundant, else, necessary. What do you think about it?
- I didn't think about relations, since that's something we would do in the Friday meeting, fyi.

Here is the current status of the diagram:
![class diagram - page 1](https://cloud.githubusercontent.com/assets/7188811/23918374/65b71770-08fb-11e7-9f7e-f29197d65459.png)

**Comment by YmirKhang** [comment]
I think its definitely necessary. Other than do we want media items to be publicly available as it is published? If it's not we can create an abstract Item class and extend both media item and cultural heritage item from it. Would it be absurd?

**Comment by egemahlec** [comment]
In my opinion, depend on the answers of the question below, my answer will change.

- Is  only the owner of the CulturalHeritage allowed to add a MediaItem? (My opinion : Every registered user is allowed to add media item to any Cultural Heritage Item)
 If answer is YES : It is reduntant.
 If answer is NO : It is not reduntant. 

I think we need to first clarify this point by getting customer's opinion and we refactor our class diagram according to this answer.

**Comment by yigitozkavci** [comment]
@egem I agree, let's leave that field for the later modification.
What about the rest of the diagram? Any feedbacks on them? @egem @emir350z

**Comment by YmirKhang** [comment]
I think all the necessary classes are created. We just need to talk about the relations tomorrow. And also we should think about the recommendation mechanisms etc.

**Comment by yigitozkavci** [comment]
This is the final version of the class diagram. Thanks @emir350z @ramazankani @egem 
![imageedit_4_8826998334](https://cloud.githubusercontent.com/assets/7188811/24050727/73bad3fe-0b38-11e7-8b4a-483b5e125adb.png)
