### ISSUE TITLE
Refactor the class diagram by adding constructors

### ISSUE THREAD

**Issue by yigitozkavci** [bounswe/bounswe2017group10#49]
These classes need constructors:

- [x] User
- [x] AudioMediaItem
- [x] VideoMediaItem
- [x] ImageMediaItem
- [x] Comment
- [x] Annotation
- [x] CulturalHeritage

**Comment by yigitozkavci** [comment]
![class diagram - page 1](https://cloud.githubusercontent.com/assets/7188811/24321147/eabbe676-114d-11e7-9be0-2fbe85b3e3f6.png)

I added them with the `<<constructor>>` notation, what do you think? @egem @emir350z

**Comment by yigitozkavci** [comment]
Added the `CulturalHeritage` constructor
![class diagram - page 1 1](https://cloud.githubusercontent.com/assets/7188811/24321162/7457d070-114e-11e7-982a-f7ea62d86db8.png)

**Comment by YmirKhang** [comment]
Good job
