### ISSUE TITLE
API tasks (@all team)

### ISSUE THREAD

**Issue by buseece** [bounswe/bounswe2017group10#61]
We need to create an API and all team members shall contribute to this process. In order to guarantee that we are doing it correctly I suggest to make task division between the members.

Below is the list of tasks I find useful for our project, feel free to suggest new topics or to comment on the existing ones so that we can agree on a list of tasks.

If you are agree with the existing topics, please take one of the tasks and assign it to yourself and implement it. **Do not forget to check the requirements before starting to implement.**

- [x] initial configuration of the API @yigitozkavci

- [x] add user @buseece

- [x] edit user @buseece

- [x] add a cultural heritage item @emir350z

- [x] retrieve all cultural heritage items @emir350z

- [x] retrieve a cultural heritage item @ramazankani

- [x] delete a cultural heritage item @bounaykut

- [x] update a cultural heritage item @bounaykut

- [x] retrieve media items @egem 

- [x] add a media item @egem

- [ ] write API documentation (preferably with Swagger)

**Comment by YmirKhang** [comment]
@bounaykut Aykut I have done the retrieve all cultural heritage items part.

**Comment by buseece** [comment]
It is going well with the development part, the only thing needed is to test them.

> Test your API using a tool like Postman, HTTPGet.
It is from our HW description. 

I tried to integrate Postman with out Git account, but I would like to hear your ideas about how to use it

**Comment by buseece** [comment]
Apparently we need to make these tasks:

4) You must use the API to fetch and process some content. (GET)
5) You must create content to use API. (POST)
6) Create a RESTful API for your application.
6) Test your API using a tool like Postman, HTTPGet.

It is in Turkish but I find it very related to our task:
http://blog.cronom.com/restwithwebapi

**Comment by YmirKhang** [comment]
All the tasks are done, what we can do now is : 

- [ ]  Error Handling (Like invdalid email or invalid queries)

- [x] Retrieving user lists based on different parameters

- [x] Create a documentation with the screenshots.
